export enum RouteUrl {
    HOME = '/home',
    CART = '/cart',
    AUTH = '/auth',
    SIGNIN = '/auth/signin',
    SIGNUP = '/auth/signup',
    FEED = '/feed',
    INSTRUCTOR = '/instructor',
    ADMIN = '/admin',
    ADMIN_NEW_ELEMENT = '/new',
    SEARCH = '/search',
    RESULTS = '/search/results',
    COURSE ='/course',
    EVENT = '/event',
    USER = '/user',
    NEW_ITEM = '/new',
    NEW_EVENT = '/new/event',
    NEW_COURSE = '/new/course',
    NEW_TITLE = '/title',
    NEW_CATEGORY = '/category',
    NEW_PRICE = '/price',
    NEW_MEDIA = '/media',
    NEW_DATES = '/dates',
    NEW_LOCATION = '/lieu',
    NEW_COMPLETED = '/completed', 
}
