export enum Database {

    USERS = '/users',
    COURSES = '/items/courses',
    COURSE = '/course',
    RATINGS = '/ratings',
    EVENTS = '/items/events',
    EVENT = '/event',
    ITEMS = '/items',
    ITEMS_VIEW = '/itemsViews',
    ITEM_TYPE = '/type',
    AUTHORS = '/authors',
    AUTHOR = '/author',
    CATEGORY = '/category',
    CATEGORIES = '/categories',
    TAGS = '/tags',
    LOCATION = '/location',
    DATA_COURSES = '/data/courses',
    DATA_INSTRUCTORS = '/data/instructors',
    DATA_COURSESOFINSTRUCTOR = '/data/coursesOfInstructor',
    DATA_CATEGORIES = '/data/categories',
    DATA_COURSESOFCATEGORY = '/data/coursesOfCategory',
    SUB_CATEGORIES = '/subCategories',
    SUB_CATEGORY = '/subCategory',
    MODULES = '/modules',
    CHAPTERS = '/chapters',
    DEFAULT_IMG_COURSE = 'https://firebasestorage.googleapis.com/v0/b/network-55b29.appspot.com/o/images%2Fitems%2Fcourse-default.jpg?alt=media&token=3ec80636-6ec7-4593-90c0-84023b01ab51',
    DEFAULT_IMG_EVENT = 'https://firebasestorage.googleapis.com/v0/b/network-55b29.appspot.com/o/images%2Fitems%2Fcalendrier.jpg?alt=media&token=6611a254-4d7f-4703-97a0-dda6ce937dc9',
    DEFAULT_PP_USER = 'https://firebasestorage.googleapis.com/v0/b/network-55b29.appspot.com/o/images%2Fusers%2Fuser-default.png?alt=media&token=bacaac7c-2e1b-4d24-8205-0964e65df549',
}
